### ISSUE TITLE
Feature requests: Adding cache

### ISSUE THREAD

**Issue by Der4NDR3** [ThomasLeister/gravatar-privacy-proxy#1]
Hi Thomas,

First I have to say, very great plug in. Well done !
Can you add a local cache for the gravatar icons please ?
This would help to reduce the HTTP request for sites with many comments.

**Comment by ThomasLeister** [comment]
Adding a cache is already on my to-do list :) I'm pretty busy at the moment, but as soon as there's time I will add a local cache to reduce the number of HTTP requests.

**Comment by ThomasLeister** [comment]
Caching is now implemented in my current dev version. The new version will be released soon :)

**Comment by ThomasLeister** [comment]
New version with caching support is released :)

**Comment by mritzmann** [comment]
Bei den `releases` fehlt die aktuelle `0.3.0`.

**Comment by ThomasLeister** [comment]
Ist erledigt!
